# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 

  config.vm.define "nginx" do |nginx|
  nginx.vm.box = "ubuntu/bionic64"
  nginx.vm.network "private_network", type: "dhcp", ip: "192.168.1.3"
  nginx.vm.provision "shell", path: "provision/nginx.sh"
  end
  
  # Configuration for Web Server 1
  config.vm.define "web1" do |web1|
  web1.vm.box = "ubuntu/bionic64"
  web1.vm.network "private_network", type: "dhcp", ip: "192.168.2.3"
  web1.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y nginx
  echo "This is Web Server 1" > /var/www/html/index.html
  SHELL
  end

  # Configuration for Web Server 2
  config.vm.define "web2" do |web2|
  web2.vm.box = "ubuntu/bionic64"
  web2.vm.network "private_network", type: "dhcp", ip: "192.168.3.3"
  web2.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y nginx
  echo "This is Web Server 2" > /var/www/html/index.html
  SHELL
  end

  # Configuration for Web Server 3
  config.vm.define "web3" do |web3|
  web3.vm.box = "ubuntu/bionic64"
  web3.vm.network "private_network", type: "dhcp", ip: "192.168.4.3"
  web3.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y nginx
  echo "This is Web Server 3" > /var/www/html/index.html
  SHELL
  end
    
end
